mv split_by_chr_PCA_indInd/CM051081.passed.indInd.pca.eigenvec.labeled split_by_chr_PCA_indInd/chr1.passed.indInd.pca.eigenvec.labeled
mv split_by_chr_PCA_indInd/CM051082.passed.indInd.pca.eigenvec.labeled split_by_chr_PCA_indInd/chr2.passed.indInd.pca.eigenvec.labeled
mv split_by_chr_PCA_indInd/CM051083.passed.indInd.pca.eigenvec.labeled split_by_chr_PCA_indInd/chr3.passed.indInd.pca.eigenvec.labeled
mv split_by_chr_PCA_indInd/CM051084.passed.indInd.pca.eigenvec.labeled split_by_chr_PCA_indInd/chr4.passed.indInd.pca.eigenvec.labeled
mv split_by_chr_PCA_indInd/CM051085.passed.indInd.pca.eigenvec.labeled split_by_chr_PCA_indInd/chr5.passed.indInd.pca.eigenvec.labeled
mv split_by_chr_PCA_indInd/CM051086.passed.indInd.pca.eigenvec.labeled split_by_chr_PCA_indInd/chr6.passed.indInd.pca.eigenvec.labeled
mv split_by_chr_PCA_indInd/CM051087.passed.indInd.pca.eigenvec.labeled split_by_chr_PCA_indInd/chr7.passed.indInd.pca.eigenvec.labeled
mv split_by_chr_PCA_indInd/CM051088.passed.indInd.pca.eigenvec.labeled split_by_chr_PCA_indInd/chr8.passed.indInd.pca.eigenvec.labeled
mv split_by_chr_PCA_indInd/CM051089.passed.indInd.pca.eigenvec.labeled split_by_chr_PCA_indInd/chr9.passed.indInd.pca.eigenvec.labeled
mv split_by_chr_PCA_indInd/CM051090.passed.indInd.pca.eigenvec.labeled split_by_chr_PCA_indInd/chr10.passed.indInd.pca.eigenvec.labeled
mv split_by_chr_PCA_indInd/CM051091.passed.indInd.pca.eigenvec.labeled split_by_chr_PCA_indInd/chr11.passed.indInd.pca.eigenvec.labeled
mv split_by_chr_PCA_indInd/CM051092.passed.indInd.pca.eigenvec.labeled split_by_chr_PCA_indInd/chr12.passed.indInd.pca.eigenvec.labeled
mv split_by_chr_PCA_indInd/CM051093.passed.indInd.pca.eigenvec.labeled split_by_chr_PCA_indInd/chr13.passed.indInd.pca.eigenvec.labeled
mv split_by_chr_PCA_indInd/CM051094.passed.indInd.pca.eigenvec.labeled split_by_chr_PCA_indInd/chr14.passed.indInd.pca.eigenvec.labeled
mv split_by_chr_PCA_indInd/CM051095.passed.indInd.pca.eigenvec.labeled split_by_chr_PCA_indInd/chr15.passed.indInd.pca.eigenvec.labeled
mv split_by_chr_PCA_indInd/CM051096.passed.indInd.pca.eigenvec.labeled split_by_chr_PCA_indInd/chr16.passed.indInd.pca.eigenvec.labeled
mv split_by_chr_PCA_indInd/CM051097.passed.indInd.pca.eigenvec.labeled split_by_chr_PCA_indInd/chr17.passed.indInd.pca.eigenvec.labeled
mv split_by_chr_PCA_indInd/CM051098.passed.indInd.pca.eigenvec.labeled split_by_chr_PCA_indInd/chr18.passed.indInd.pca.eigenvec.labeled
mv split_by_chr_PCA_indInd/CM051099.passed.indInd.pca.eigenvec.labeled split_by_chr_PCA_indInd/chr19.passed.indInd.pca.eigenvec.labeled
mv split_by_chr_PCA_indInd/CM051100.passed.indInd.pca.eigenvec.labeled split_by_chr_PCA_indInd/chr20.passed.indInd.pca.eigenvec.labeled
mv split_by_chr_PCA_indInd/CM051101.passed.indInd.pca.eigenvec.labeled split_by_chr_PCA_indInd/chr21.passed.indInd.pca.eigenvec.labeled
mv split_by_chr_PCA_indInd/CM051102.passed.indInd.pca.eigenvec.labeled split_by_chr_PCA_indInd/chr22.passed.indInd.pca.eigenvec.labeled
mv split_by_chr_PCA_indInd/CM051103.passed.indInd.pca.eigenvec.labeled split_by_chr_PCA_indInd/chr23.passed.indInd.pca.eigenvec.labeled
mv split_by_chr_PCA_indInd/CM051104.passed.indInd.pca.eigenvec.labeled split_by_chr_PCA_indInd/chr24.passed.indInd.pca.eigenvec.labeled
mv split_by_chr_PCA_indInd/CM051105.passed.indInd.pca.eigenvec.labeled split_by_chr_PCA_indInd/chr25.passed.indInd.pca.eigenvec.labeled
mv split_by_chr_PCA_indInd/CM051106.passed.indInd.pca.eigenvec.labeled split_by_chr_PCA_indInd/chr26.passed.indInd.pca.eigenvec.labeled
mv split_by_chr_PCA_indInd/CM051107.passed.indInd.pca.eigenvec.labeled split_by_chr_PCA_indInd/chr27.passed.indInd.pca.eigenvec.labeled
mv split_by_chr_PCA_indInd/CM051108.passed.indInd.pca.eigenvec.labeled split_by_chr_PCA_indInd/chr28.passed.indInd.pca.eigenvec.labeled
mv split_by_chr_PCA_indInd/CM051109.passed.indInd.pca.eigenvec.labeled split_by_chr_PCA_indInd/chr29.passed.indInd.pca.eigenvec.labeled
mv split_by_chr_PCA_indInd/CM051110.passed.indInd.pca.eigenvec.labeled split_by_chr_PCA_indInd/chr30.passed.indInd.pca.eigenvec.labeled
mv split_by_chr_PCA_indInd/CM051111.passed.indInd.pca.eigenvec.labeled split_by_chr_PCA_indInd/chr31.passed.indInd.pca.eigenvec.labeled
mv split_by_chr_PCA_indInd/CM051112.passed.indInd.pca.eigenvec.labeled split_by_chr_PCA_indInd/chr32.passed.indInd.pca.eigenvec.labeled
mv split_by_chr_PCA_indInd/CM051113.passed.indInd.pca.eigenvec.labeled split_by_chr_PCA_indInd/chr33.passed.indInd.pca.eigenvec.labeled
mv split_by_chr_PCA_indInd/CM051114.passed.indInd.pca.eigenvec.labeled split_by_chr_PCA_indInd/chr34.passed.indInd.pca.eigenvec.labeled
mv split_by_chr_PCA_indInd/CM051115.passed.indInd.pca.eigenvec.labeled split_by_chr_PCA_indInd/chr35.passed.indInd.pca.eigenvec.labeled
mv split_by_chr_PCA_indInd/CM051116.passed.indInd.pca.eigenvec.labeled split_by_chr_PCA_indInd/chr36.passed.indInd.pca.eigenvec.labeled
mv split_by_chr_PCA_indInd/CM051117.passed.indInd.pca.eigenvec.labeled split_by_chr_PCA_indInd/chr37.passed.indInd.pca.eigenvec.labeled
mv split_by_chr_PCA_indInd/CM051118.passed.indInd.pca.eigenvec.labeled split_by_chr_PCA_indInd/chr38.passed.indInd.pca.eigenvec.labeled
mv split_by_chr_PCA_indInd/CM051119.passed.indInd.pca.eigenvec.labeled split_by_chr_PCA_indInd/chr39.passed.indInd.pca.eigenvec.labeled
mv split_by_chr_PCA_indInd/CM051120.passed.indInd.pca.eigenvec.labeled split_by_chr_PCA_indInd/chr40.passed.indInd.pca.eigenvec.labeled
mv split_by_chr_PCA_indInd/CM051121.passed.indInd.pca.eigenvec.labeled split_by_chr_PCA_indInd/chr41.passed.indInd.pca.eigenvec.labeled
mv split_by_chr_PCA_indInd/CM051122.passed.indInd.pca.eigenvec.labeled split_by_chr_PCA_indInd/chr42.passed.indInd.pca.eigenvec.labeled
#mv split_by_chr_PCA_indInd/CM051123.passed.indInd.pca.eigenvec.labeled split_by_chr_PCA_indInd/chrW.passed.indInd.pca.eigenvec.labeled
#mv split_by_chr_PCA_indInd/CM051124.passed.indInd.pca.eigenvec.labeled split_by_chr_PCA_indInd/chrZ.passed.indInd.pca.eigenvec.labeled
